[package]
name = "argon2-wasm"
version = "0.1.0"
authors = ["L4ngu0r <stew.roulleau@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
rust-argon2 = { version = "0.8", default-features = false }

[profile.release]
lto = true
opt-level = 3
